export const FETCH_ONE_DAY_WEATHER = "FETCH_ONE_DAY_WEATHER";
export const FETCH_ONE_DAY_WEATHER_SUCCESS = "FETCH_ONE_DAY_WEATHER_SUCCESS";
export const FETCH_ONE_DAY_WEATHER_ERROR = "FETCH_ONE_DAY_WEATHER_ERROR";
