export const FETCH_ONE_DAY_WEATHER = "FETCH_ONE_DAY_WEATHER";
export const FETCH_ONE_DAY_WEATHER_SUCCESS = "FETCH_ONE_DAY_WEATHER_SUCCESS";
export const FETCH_ONE_DAY_WEATHER_ERROR = "FETCH_ONE_DAY_WEATHER_ERROR";

export const FETCH_FIVE_DAYS_WEATHER = "FETCH_FIVE_DAYS_WEATHER";
export const FETCH_FIVE_DAYS_WEATHER_SUCCESS =
  "FETCH_FIVE_DAYS_WEATHER_SUCCESS";
export const FETCH_FIVE_DAYS_WEATHER_ERROR = "FETCH_FIVE_DAYS_WEATHER_ERROR";

export const FETCH_SELF_LOCATION_ONE_DAY_WEATHER =
  "FETCH_SELF_LOCATION_ONE_DAY_WEATHER";
export const FETCH_SELF_LOCATION_ONE_DAY_WEATHER_SUCCESS =
  "FETCH_SELF_LOCATION_ONE_DAY_WEATHER_SUCCESS";
export const FETCH_SELF_LOCATION_ONE_DAY_WEATHER_ERROR =
  "FETCH_SELF_LOCATION_ONE_DAY_WEATHER_ERROR";

export const FETCH_SELF_LOCATION_FIVE_DAYS_WEATHER =
  "FETCH_SELF_LOCATION_FIVE_DAYS_WEATHER";
export const FETCH_SELF_LOCATION_FIVE_DAYS_WEATHER_SUCCESS =
  "FETCH_SELF_LOCATION_FIVE_DAYS_WEATHER_SUCCESS";
export const FETCH_SELF_LOCATION_FIVE_DAYS_WEATHER_ERROR =
  "FETCH_SELF_LOCATION_FIVE_DAYS_WEATHER_ERROR";

export const SET_CURRENT_WEATHER_TO_VIEW = "SET_CURRENT_WEATHER_TO_VIEW";
export const SET_WEATHER_TIME = "SET_WEATHER_TIME";
export const REFRESH_WEATHER = "REFRESH_WEATHER";
